package com.example.FlightSystemBackend.JPARelies.DTO;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.Id;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class Contact {

    //TODO make primary key autogenerated

    @Id
    private int messageId ;
    private String senderName ;
    private String content ;

}
